name: fsgen
description: Code generator for projects using Serverpod and Riverpod
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  path: ^1.9.1
  glob: ^2.1.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
